### ISSUE TITLE
When Rhino Button is pressed, No Revit Interaction Possible when Rhino is maximized

### ISSUE THREAD

**Issue by shu-toz** [mcneel/rhino.inside#106]
Hi All,

The Rhino button stops all Revit interactivity until the Rhino window is closed (When Rhino is maximized)

Also I've noticed if you launch Rhino and then launch Grasshopper as a rhino command, the "Pick Revit Element" command within grasshopper freezes the entire thing.

**Comment by kike-garbo** [comment]
Fixed in #114
