### ISSUE TITLE
Rhino Inside Revit will not load when PyRevit is loaded

### ISSUE THREAD

**Issue by gmb99** [mcneel/rhino.inside#108]
Rhino Inside Revit will not load when PyRevit is loaded. Receive Rhino License Manager Error Message. If I unload PyRevit Rhino within Revit will Load. I would like to have both apps available. I will also post to PyRevit. Issue maybe incompatible Python code?

Greg

![image](https://user-images.githubusercontent.com/41219070/59570119-1f60e680-9048-11e9-970d-fb5d254499f8.png)

**Comment by scotttd** [comment]
Interesting.  I was able to run with this version of PyRevit running:

![image](https://user-images.githubusercontent.com/887876/59574812-8f359800-906d-11e9-9a56-2c83133300a0.png)

I am running the latest Rhino WIP with Revit 2019. How does that differ from your setup?

This is the only discourse I see: https://discourse.mcneel.com/t/rhino-6-license-manager-initialization-failed-with-error-200/54292 . But if it comes and goes with loading PyRevit.  There must be a conflict.

**Comment by scotttd** [comment]
I am seeing some instability when trying to select geometry from Grasshopper.  In your case Rhino would not load at all?

**Comment by kike-garbo** [comment]
Seams same problem as #66

**Comment by ArchitectTaeyoon** [comment]
experienced same problem today.
Was in the middle of scripting python in Dynamo, then tried to turn on RhinoInside, and got the same error.
Restarting the software made the error go away for me.

**Comment by yishizu** [comment]
![error](https://user-images.githubusercontent.com/48244588/61270093-94584500-a7db-11e9-95a5-af1716d60393.JPG)
same error....

**Comment by scotttd** [comment]
@gmb99 - Last evening we released a new Rhino 7 WIP version.  It approaches the JSON libraries differently and we hope will solve the conflict with PyRevit.  Please install the newest Rhino 7 WIP update.  I hope you will see a fix.

**Comment by scotttd** [comment]
Here are instructions to fix the PyRevit conflict: the PyRevit conflict: https://github.com/eirannejad/pyRevit/issues/628

Looks like Ehsan will be implementing a more permanent fix in the next version.

Can everyone here give this a try and see if it fixes the problem?

**Comment by Sonderwoods** [comment]
Works fine for me if I open rhinoinside before i load a revit file!
simply hide the start dashboard in revit and load rhinoinside as the first thing after loading revit.
