### ISSUE TITLE
Sample Grasshopper files not available

### ISSUE THREAD

**Issue by gmb99** [mcneel/rhino.inside#109]
I am not finding the sample grasshopper files with my Rhino inside Revit download. Is it possible to provide a link to the sample files?
Thank-you Greg

**Comment by kike-garbo** [comment]
Here there are https://github.com/mcneel/rhino.inside/tree/master/Autodesk/Revit/src/RhinoInside.Revit/Samples

**Comment by kike-garbo** [comment]
Now Sample files are installed at %APPDATA%\Autodesk\Revit\Addins\%RevitVersionNumber%\RhinoInside.Revit
