### ISSUE TITLE
Rhino Inside breaks Revit Keyboard Shortcuts

### ISSUE THREAD

**Issue by vasshaug** [mcneel/rhino.inside#111]
Versions: Revit 2019.2.10.7 and Rhino Work In Progress (7.0.19163.2505, 2019-06-12).

The Revit Keyboard Shortcuts file (%APPDATA%\Autodesk\Revit\Autodesk Revit 2019\KeyboardShortcuts.xml) get's overwritten by Rhino Inside, and subsequently all Revit shortcuts disappear.

![image](https://user-images.githubusercontent.com/5300197/60096643-c41eaa80-9751-11e9-8d8a-aaf0d1973d6b.png)

![image](https://user-images.githubusercontent.com/5300197/60096651-c84ac800-9751-11e9-9dd8-a95f32d99bfd.png)

**Comment by kike-garbo** [comment]
Fixed in #115
