### ISSUE TITLE
Missing Namespace / Target Framework Issue + Fix

### ISSUE THREAD

**Issue by anddoyoueverfeel** [mcneel/rhino.inside#12]
My co-worker and I had some trouble getting the samples to work initially. After troubleshooting, this is the solution we found. Hopefully this is the right place to post this, and it helps others.

![01](https://user-images.githubusercontent.com/12450940/48211430-76cb0580-e347-11e8-8082-240634e75d2d.jpg)
![02](https://user-images.githubusercontent.com/12450940/48211438-7894c900-e347-11e8-9300-a9131df118f9.jpg)
![03](https://user-images.githubusercontent.com/12450940/48211442-7a5e8c80-e347-11e8-9fc9-a9ae1cbe874d.jpg)

The .NET package is available for download here:
https://www.microsoft.com/net/download

**Comment by kike-garbo** [comment]
Projects come preconfigured to compile using **.NET Framework 4.7**
You can install it using this...

![install-other-frameworks](https://user-images.githubusercontent.com/3530512/48214778-fcb77280-e380-11e8-9089-eb460c541b42.png)

**Comment by kike-garbo** [comment]
Added to the prerequisites section.
Thanks for point this out!!
