### ISSUE TITLE
can't find Rhino 7 while it is installed

### ISSUE THREAD

**Issue by netsonicyxf** [mcneel/rhino.inside#124]
Win10 x64, Revit 2019.2，rhino_en-us_**7.0.19189.20125**

while press rhino.inside on Revit, it shows 
Unsupported Rhino WIP version
Expected version is 7.0.19148 or above
Installed version: 0.0.0.0

**Comment by kike-garbo** [comment]
Now the addon looks into the Rhino registry to know where Rhino is installed in case the user don't install Rhino in the default location.
Changes are made in the #128

**Comment by netsonicyxf** [comment]
The new addon fixes the issue.
Thanks!
