### ISSUE TITLE
Add.Column.ByCurve does not work

### ISSUE THREAD

**Issue by maito78** [mcneel/rhino.inside#125]
When using the AddColumn.ByCurve nothing happens in Revit. The component gives a different output compared with the component AddBeam.ByCurve. (See image below)

Revit 2019 - 19.0.0.405 20180216_1515(x64)
Rhino - (7.0.19183.10495, 07/02/2019)

![screen](https://user-images.githubusercontent.com/7395751/61361686-27978600-a881-11e9-9d25-574efbce41f7.png)

**Comment by kike-garbo** [comment]
Could you please test it again with the last version?

**Comment by maito78** [comment]
Perfect, now it works!
Thanks for your help.
