### ISSUE TITLE
Rhino.Inside JSON error

### ISSUE THREAD

**Issue by jsimps78** [mcneel/rhino.inside#151]
I have experience with Rhino, grasshopper and Revit, but I'm not too familiar with the whole coding language, so I have absolutely no idea what this error message means: 

Cannot deserialize the current JSON object (e.g.{name":value"}) into type 'System.Collections.Generic.IReadOnlyDictionary'2[System.String,McNeel.RhinoAccounts.OpenIDConnectToken+RhinoAccountsGroup]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly. To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array ot List<t>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object. Path 'OpenIdToken.MemberGroups.5272672149700608', line 1, position 1148.

After downloading Rhino.Inside, I open Revit, create a new project, go to add-ins and click on RhinoWIP and this is the message I get. I have no idea what it means or how to fix it

Please help...

**Comment by scotttd** [comment]
Yes, we are trying to chase this error.  Can you answer these questions to help:

1. What version of Revit?
2. Is this today's Rhino 7 WIP? Can you install it to see?
3. What other Revit plugins do you have running?  PyRevit?
4. If you run Rhino 7 WIP on its own does it work? If it does work on its own, does it then run in Revit?

With the ansers to these questions I hope we can fix it.

**Comment by jsimps78** [comment]
1. Revit 2019
2. Yes, its Rhino WIP 7.0.19212.4535
3. Don't have PyRevit- I have Enscape if that counts. I am not quite sure about the rest but here are some screen grabs of the addins/plugins

![plugins](https://user-images.githubusercontent.com/54040564/62899045-ecc02b00-bd24-11e9-983d-af26047424a6.JPG)

![addins](https://user-images.githubusercontent.com/54040564/62899053-f053b200-bd24-11e9-8fae-bad863125b9e.JPG)

4. Yes, Rhino 7 WIP runs on it's own but I have had no success in running it in Revit yet due to the error. Also after the error pops up, Revit force quits
Thank you

**Comment by scotttd** [comment]
We created a new Rhino 7 WIP that allows for logging the conflicts with support frameworks.  We have successfully solved this problem with other plugins.  Can you install the latest Rhino 7 WIP and follow the Log file instructions.  Then, once Rhino.inside runs in Revit the Log file will show details that may be helpful.

Instructions:
1. Install the latest WIP
2. Create a blank text file called RhinoAssemblyResolveLog.txt on the desktop
3. Then run Rhino.inside Revit and Grasshopper if possible.

Send us back the TXT file and we can take a look.  You may want to name the file something different on your desktop afterwords  so it does not continue to log.

**Comment by jsimps78** [comment]
I installed the latest WIP and tested it again- It actually works now! Thank you very much
