### ISSUE TITLE
Rhino Inside on CPython cannot load, due to a mismatch in installation path

### ISSUE THREAD

**Issue by gonzalocasas** [mcneel/rhino.inside#183]
*Edit:* updated to reflect the fact that the second issue went away. 

----

I bumped into ~two~ one minor problem while test Rhino Inside:

* Invoking `rhinoinside.load()` fails because the default path seems to have changed from `%Program Files%\Rhino WIP\System` tp `%Program Files%\Rhino 7 WIP\System`.

**Comment by gonzalocasas** [comment]
Is this fixed with pull request #128 ?

**Comment by sbaer** [comment]
No.
That logic is what needs to be added to our CPython implementation to find Rhino. Same logic, different code to add it to

**Comment by sbaer** [comment]
No, that PR is not for python. I need to do something similar though

**Comment by sbaer** [comment]
@gonzalocasas I just uploaded a new version of rhinoinside to PyPi.org. Please try this new version to see if it works better for you.

**Comment by sbaer** [comment]
Closed in #209
