### ISSUE TITLE
Rhino inside Unity

### ISSUE THREAD

**Issue by Pixelstudio** [mcneel/rhino.inside#184]
Hi,

I'v been trying out rhino.inside in Unity, the example is working fine. i'm able to let rhino calculate some meshes and get the result back in unity.

Under window, i can start grasshopper.
Is it possible to get the result from grasshopper back in unity ?

Cheers,

**Comment by fraguada** [comment]
Grasshopper is not yet supported inside Unity. We are working on it, but it requires us to change the way that Rhino loads inside Unity, including using the Mono runtime included with Unity.

**Comment by fraguada** [comment]
@Pixelstudio This has been resolved. Check the Unity Sample 2: https://github.com/mcneel/rhino.inside/tree/master/Unity/Sample2
