### ISSUE TITLE
NuGet package for Rhino.Inside assembly resolver

### ISSUE THREAD

**Issue by pearswj** [mcneel/rhino.inside#196]
Create a NuGet package for the [Rhino.Inside assembly resolver](https://github.com/mcneel/rhino.inside/tree/master/DotNet/RhinoInside) that depends on the RhinoCommon, Grasshopper and RhinoWindows packages.

This will reduce the amount of boilerplate required to set up new Rhino.Inside projects.

See also [RH-54969](https://mcneel.myjetbrains.com/youtrack/issue/RH-54969)

**Comment by fraguada** [comment]
Does this code handle cases where RhinoCommon.dll or Grasshopper.dll would be loaded in another AppDomain, for example, one which enables Shadow Copying? I'm running into issues where a host app might have its own Assembly Resolving code and creates new AppDomains. This means that the Grasshopper.dll being called is in a different AppDomain than the one used by Rhino.

**Comment by pearswj** [comment]
The current package works on PackageReference projects, but not when packages.config is used.

>I just tried to switch over to use the Rhino.Inside nuget package for compute.rhino3d and got the following message
>```
Attempting to gather dependency information for package 'Rhino.Inside.0.1.1' with respect to project 'compute.geometry', targeting '.NETFramework,Version=v4.6.2'
Gathering dependency information took 61.75 ms
Attempting to resolve dependencies for package 'Rhino.Inside.0.1.1' with DependencyBehavior 'Lowest'
Unable to find a version of 'RhinoWindows' that is compatible with 'Rhino.Inside 0.1.1 constraint: RhinoWindows (>= 7.0.19274.12465-wip)'.
Time Elapsed: 00:00:00.1081074
========== Finished ==========
```

Looks like this is a known issue with packages that have a stable version but have prerelease dependencies.

NuGet/Home#2944
