### ISSUE TITLE
Host application resolves assemblies in its own AppDomain

### ISSUE THREAD

**Issue by fraguada** [mcneel/rhino.inside#197]
I'm running into situations where a host application chooses to resolve and load assemblies in its own AppDomain (creates a specific AppDomain). The Host application might chose to do this in order to support Shadow Copying, for example.
The issue this causes is mainly experienced when using the Grasshopper api via Grasshopper.dll. In this situation, if the Grasshopper plugin is loaded via the `PlugIn.LoadPlugIn(GrasshopperGuid)`, subsequent calls to the Grasshopper namespace are calling a Grasshopper.dll loaded in a different AppDomain than that where Rhino has loaded Grasshopper.dll. This means that one cannot actually call any of the Grasshopper API.
What would be the solution for this case? 
Is this something that would need to be changed in the Rhino source code, or is this something that can be handled by the code referenced to in this issue: https://github.com/mcneel/rhino.inside/issues/196?

**Comment by sbaer** [comment]
What host application is this? I've only ever seen ASP.NET use separate AppDomains and they are pretty much being phased out in new versions of .NET Core

**Comment by fraguada** [comment]
This is in USharp: https://github.com/pixeltris/USharp
The developer responded with several ways to get around this:
1. Use the .NET Core (3.0 Preview) runtime:
> if you use .net core it should always use the main appdomain as .net core doesn't support multiple appdomains
2. Load assemblies without context 
> https://github.com/pixeltris/USharp/blob/master/Managed/UnrealEngine.Runtime/Loader/EntryPoint.cs#L40 
> if set this to true, this will use the main appdomain (and stop hotreload from working)
3. Disable AppDomain Shadow Copying
> you could try to disable ShadowCopyAssembly but I think that would just break things (I think at some point I supported loading from byte arrays as an alternative, but I think i removed it due to dependency issues).

Doing #2 solves the issue in USharp. #3 by itself does nothing. Tried going through and setting up my system for .NET Core 3, but kept running into issues. For this particular case we can make due with #2.

I have tested #2 and #3, and found both need to be used for Grasshopper to work as expected. I'd prefer a method by which we do not have to modify USharp, so I will test #1 after
