### ISSUE TITLE
REVIT - External Tools - External Tool Failure 

### ISSUE THREAD

**Issue by ssiimmoonnee** [mcneel/rhino.inside#230]
Revit cannot run the external application "Rhino Inside Revit". Contact the provider for assistance. Information they provided to Revit about their identity: Robert McNeel & Associates.

System.Reflection.TargetInvocationException
Exception has been thrown by the target of an invocation.

Revit 2017 and 2019
![image](https://user-images.githubusercontent.com/25032727/67558234-871df100-f70e-11e9-95b5-5e6656742642.png)

**Comment by kike-garbo** [comment]
Recently we introduced changes in this area.
Could you please update your local copy and test it again?

**Comment by ssiimmoonnee** [comment]
Works now. Thanks!
