### ISSUE TITLE
RhinoLibrary loading

### ISSUE THREAD

**Issue by corbane** [mcneel/rhino.inside#248]
Hello,

It's a bit catastrophic, the examples don't work. suddenly it does not explain much.

They will search on NuGet, RhinoCommon.dll, Grasshopper.dll, ... and even RhinoInside. Is that normal ?

In the file DotNet/RhinoInside/Resolver.cs, line 39
`double.TryParse(children[i], out double d)`  fails depending on the country.
use for example
` double.TryParse("7.0", NumberStyles.Any, CultureInfo.InvariantCulture , out double b)`

I only managed to make it work DotNet/WinFormsApp,
the others fail, often due to RhinoLibrary loading which applications cannot find.

why RhinoInside.dll is not directly in Rhino's directory ? (C:\Program Files\Rhino 7 WIP)

**Comment by sbaer** [comment]
Please report a single issue at a time. I'm going to assume this issue is to tune up `double.TryParse` in the resolver to work with InvariantCulture.

If there is a different issue that you would like me to address, please create a new github issue. Thanks 👍

**Comment by corbane** [comment]
Not really,

The issue is rather a request:
"Simplify loading of RhinoLibrary and RhinoCore"

Depending on the country or the installation `AppDomain.CurrentDomain.AssemblyResolve += ...` fail

**Comment by sbaer** [comment]
I'm reopening this as we just need to fix a TryParse and publish new nuget packages for Rhino.Inside
