### ISSUE TITLE
Launch Rhino using Rhino.Inside AutoCAD and output geometry

### ISSUE THREAD

**Issue by ThomasMahon** [mcneel/rhino.inside#288]
@kike-garbo is it possible to launch Rhino and add geometry instantiated from RhinoCommon in an AutoCAD plugin?

**Comment by sbaer** [comment]
I believe that is what the acad sample in this repo does
https://github.com/mcneel/rhino.inside/tree/master/Autodesk/AutoCAD

**Comment by ThomasMahon** [comment]
Hi @sbaer I've used that to test and while it works, it doesn't launch the Rhino application. I tried some hacks to force Rhino to open but it caused exceptions. I'm targeting AutoCAD 2024 whereas the example used a much older version so not sure if some framework issue is preventing it from launching?

**Comment by sbaer** [comment]
Rhino is launched, but it is launched without UI. If you want user interface, you should construct the RhinoCore instance with the WindowStyle.Normal parameter.
https://github.com/mcneel/rhino.inside/blob/master/Autodesk/AutoCAD/Plugin.cs#L51

something like
```c#
var style = Rhino.Runtime.InProcess.WindowStyle.Normal;
m_rhino_core = new Rhino.Runtime.InProcess.RhinoCore(new[] { $"/scheme={SchemeName}" }, style);
```

**Comment by ThomasMahon** [comment]
Awesome, that works. Thanks
