### ISSUE TITLE
Relaunch Rhino app if closed when attached to AutoCAD

### ISSUE THREAD

**Issue by ThomasMahon** [mcneel/rhino.inside#289]
Is it possible to relaunch the Rhino app when launched inside AutoCAD. 

Example: 
Rhino launches when AutoCAD starts (which is great for debugging purposes).
I close Rhino application after its launched. 

How can I re-open it? 

If I launch Rhino via its short cut icon its not 'attached'. So maybe a better question to ask, is how can I re-open the attached version. I don't mind if this has a programmatic solution since the end user is not interacting with Rhino, we just need it open for software development purposes.

**Comment by sbaer** [comment]
Rhino's DLLs are loaded into AutoCAD's process when running as Rhino.Inside. These DLLs can not be unloaded from a process.
