### ISSUE TITLE
BricsCAD

### ISSUE THREAD

**Issue by fsat12** [mcneel/rhino.inside#29]
Hi I wanted to test Inside.Rhino with BricsCad.
I got stuck with RhinoInside.BricsCAD.sln
If I want to open with Visual Studio 2017 I got an error
![image](https://user-images.githubusercontent.com/44390579/51128289-c6d2b680-1827-11e9-9610-d9a38f17ab59.png)

The selected File is not a valid solution file

can anybody help?

**Comment by dalefugier** [comment]
`RhinoInside.BricsCAD.sln` opens fine here with Visual Studio 2017. It's just an xml file - you should be able to view it with Notepad.
