### ISSUE TITLE
Wish: Set Parameter in GH for Revit

### ISSUE THREAD

**Issue by josols** [mcneel/rhino.inside#50]
It would be really good if a node for setting parameters in Revit existed based on element, parameter name and value.

**Comment by kike-garbo** [comment]
I did a commit with this implemented?
Does it work for you?

**Comment by josols** [comment]
Yep, it did. Had to close down grasshopper and Revit first though, not sure what I did wrong. On a sidenote I think it would be to use the string version of the parameter as input to the node. At least Dynamo people is used to that way of inputting parameter names.

**Comment by kike-garbo** [comment]
What happens then with Revit in other languages?
Do those Dynamo Workspaces still work there?
I mean, if you bind the property by name then binding will be broken when you share this Dynamo Workspace with a french college for instance. Is'n it?

**Comment by josols** [comment]
I have yet to get feedback that this creates troubles of any magnitude. People will then change the string input to French. For me it seems easier at least, but I'm sure there are good arguments against. :)

**Comment by kike-garbo** [comment]
Do you know Element.Decompose component?
You can use it to access any parameter without typing any parameter name. Internally it stores the parameter Id for you, and it works on any Revit language.

![image](https://user-images.githubusercontent.com/3530512/55868827-8c0dbf80-5b85-11e9-9fcb-f9fa1ae1b60f.png)

**Comment by kike-garbo** [comment]
I also implemented the conversion from string.
It shows you a warning when the parameter name is not found.

![image](https://user-images.githubusercontent.com/3530512/55873550-3d195780-5b90-11e9-89a4-d0681e375240.png)

**Comment by josols** [comment]
man, you are crazy fast. With this tempo, Dynamo is out of business in a year. Thanks.
