### ISSUE TITLE
Make Extension Methods Public

### ISSUE THREAD

**Issue by sridharbaldava** [mcneel/rhino.inside#54]
Can you please make the extension methods in Convert class public?
e.g., https://github.com/mcneel/rhino.inside/blob/master/Autodesk/Revit/Convert.cs#L193

**Comment by sbaer** [comment]
Why do you need these to be public?

**Comment by sridharbaldava** [comment]
Creating some components in a separate project that rely on these conversions. Some of them already are public, so, was wondering if others can be made public as well.

**Comment by kike-garbo** [comment]
Sure, give it for granted.
Just in case you didn't see it in code if you deploy your gha in the folder %APPDATA%\Grasshopper\Libraries-Autodesk-Revit-20XX (where XX may be 17, 18 or 19) it will be automatically loaded when Grasshopper is running inside Revit.
