### ISSUE TITLE
References missing

### ISSUE THREAD

**Issue by robwood93** [mcneel/rhino.inside#64]
There are references missing for Autodesk & Rhino & Rhino.Geometry etc. within the rhino.inside solution when i open it in visual studio. this gives me many errors and does not build. Can you advise what references i need and where these references would be located please.

![image](https://user-images.githubusercontent.com/49550563/56020144-635d0580-5cfe-11e9-9484-d07e58e6a8ed.png)

**Comment by kike-garbo** [comment]
Since we are using PackageReference in the project, you need Visual Studio 15.7.
See here: https://docs.microsoft.com/nuget/reference/migrate-packages-config-to-package-reference

Is it your case?

**Comment by pearswj** [comment]
Since #56 we require Visual Studio 15.9 which includes a fix for dotnet/project-system#2129.

It might be necessary to explicitly restore the nuget packages before building; I'm not sure. (Right click on the solution in the solution explorer pane and select "Restore NuGet Packages".)
