### ISSUE TITLE
Rhinoceros License Manager Issue

### ISSUE THREAD

**Issue by alexberd** [mcneel/rhino.inside#66]
I am receiving the above error when starting Revit:
"Rhino license manager initialisation failed with error -200. Rhino will not run"

However when I run Rhino WIP on its own it does not allow to choose any valid license similar to rhino 6. Rhino WIP license page (under help->about) says 42 days left  :((

Is there any way I could define the Rhino WIP license by the plugin or the Rhino application so that I could get this plugin working in Revit?

Any advice will be really appreciated. Many thanks

**Comment by kike-garbo** [comment]
We have detected that some other Revit addons that use an other NewtonSoft Json.NET library than Rhino are not compatible with RhinoInside.

Could you please check it?
See some instructions [here](https://discourse.mcneel.com/t/licese-manager-initialization-failed-with-error-200/76575/22)

**Comment by didyoureboot** [comment]
PyRevit was causing the licence error for me. Once PyRevit was disabled rhinoinside worked.

**Comment by kike-garbo** [comment]
Thanks!!

**Comment by scotttd** [comment]
@alexberd @didyoureboot -  Last evening we released a new Rhino 7 WIP version.  Please update to that and see if it fixes the PyRevit conflict.  We hope it works.

**Comment by scotttd** [comment]
We are still chasing this problem.  WE need to try and recreate the problem here.

Can you list:
1) What version of Revit are you using?
2) What Version of PyRevit?
3) What Version of Dynamo?

We keep trying to chase this, but are having trouble finding the solution.

**Comment by scotttd** [comment]
I am not sure if you all saw the good news about the PyRevit conflict: https://github.com/eirannejad/pyRevit/issues/628
