### ISSUE TITLE
Dependency Specification for Revit Build

### ISSUE THREAD

**Issue by mitevpi** [mcneel/rhino.inside#8]
I'm trying to build the Revit samples as outlined here: https://github.com/mcneel/rhino.inside/tree/master/Autodesk/Revit

I'm having several issues with dependencies however:
![image](https://user-images.githubusercontent.com/25568566/47378013-d88f3c80-d6c4-11e8-9262-b39f65424e9a.png)

The first issue is a missing RhinoCommon dependency. For reference - I'm using the RhinoCommon package from NuGet - please advise if it should be loaded in from a local .dll instead.

The second issue is with the Eto.Forms dependency:
![image](https://user-images.githubusercontent.com/25568566/47378101-1ab87e00-d6c5-11e8-8e1b-e0df1d09aa14.png)

Any advice on either issue?

**Comment by dalefugier** [comment]
You should be referencing RhinoCommnon.dll that is included with the Rhino 7 WIP. If you don't have the Rhino 7 WIP, then you'll need to download and install it.

https://www.rhino3d.com/download/rhino/wip

-- Dale

**Comment by kike-garbo** [comment]
It seams you are trying with a DLL downloaded from somewhere.
Could you please try with this one `C:\Program Files\Rhino WIP\System\RhinoCommon.dll` ?

Projects on the repository already reference this path.
Have you installed Rhino WIP some other place maybe?
