### ISSUE TITLE
Uninstaller leaves .pdb files behind

### ISSUE THREAD

**Issue by pearswj** [mcneel/rhino.inside#82]
Hey @kike-garbo, I just tested the installer quickly and uninstalling leaves .pdb files behind, e.g. `C:\Users\will\AppData\Roaming\Autodesk\Revit\Addins\2017\RhinoInside.Revit\RhinoInside.Revit.pdb`

**Comment by kike-garbo** [comment]
Installer do not install pdb files.
Originally the project where configured to "install" the Revit addon on each build.
I changed this, now Release configuration relay on the real installer to do that.
If you remove those files, and as long as you don't build in Debug, you should not have more PDB files in the installation folder.

**Comment by pearswj** [comment]
You're right 🤦‍♂. Thanks!
