### ISSUE TITLE
Wish: Material/Name/Category input for BrepElement.ByGeometry component

### ISSUE THREAD

**Issue by josols** [mcneel/rhino.inside#83]
There is a need for adding Material, Name and Category for the Brep import to Revit. Version for Dynamo has been made here: https://github.com/dimven/SpringNodes/blob/master/Nodes/BrepShape.ByGeometry.dyf

(If readable?)

**Comment by kike-garbo** [comment]
BrepElement.ByGeometry is a basic **geometry** baker component, it bakes one DirectShape for each Brep just that no more no less.

Do you know the DirectShape.ByGeometry component is in the "Build" Panel.
The idea behind this other is to bake a **BIM** object, with Category and Name by now.
Type and material are on the list. 🙏
