### ISSUE TITLE
Revit Transaction Error

### ISSUE THREAD

**Issue by alexberd** [mcneel/rhino.inside#84]
When trying to apply a Revit Transaction I get the following error:

> Runtime error (invalidOperationException): Starting a transaction from an external application running outside of API context is not allowed.

**Comment by kike-garbo** [comment]
In order to fix this I needed to do some changes in Rhino WIP.
A new Release will be available next Tuesday with those changes included.
My plan was to do a sample using a C# Script component that shows how to use it in this repo.
I will tell you when all the pieces are in their place.

**Comment by alexberd** [comment]
Just checked the new commit and still getting the same error.
Could you please confirm if the following code in a python node in Grasshopper?

```
import rhinoscriptsyntax as rs
import clr
clr.AddReference('RevitNodes') 
import Revit
clr.AddReference('RevitAPI') 
import Autodesk
from Autodesk.Revit.DB import *
clr.AddReference('RevitAPIUI')
from Autodesk.Revit.DB import * 
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
import System
doc=DocumentManager.Instance.CurrentDBDocument
uiapp= DocumentManager.Instance.CurrentUIApplication
t = Transaction(doc, 'Place an Adaptive Component.')
t.Start()
collector = FilteredElementCollector(doc)
collector.OfCategory(BuiltInCategory.OST_Walls)
t.Commit()
a=collector
```

That is the error I am getting:
```
Runtime error (ArgumentNullException): The input argument "document" of function `anonymous-namespace'::Transaction_constructor or one item in the collection is null at line 97 of file d:\ship\2018_px64\source\revit\revitdbapi\gensrc\APIUndoTransactionProxy.cpp.
Parameter name: document

Traceback:
  line 43, in script
```

**Comment by kike-garbo** [comment]
It should work with the last update to the repo.

![image](https://user-images.githubusercontent.com/3530512/58629835-d554d280-82dd-11e9-894a-a297fe3b7b12.png)

I modified a bit your script to use RhinoInside to get acces to the active Document.

```
import clr
clr.AddReference('RhinoInside.Revit') 
from RhinoInside.Revit import Revit, Convert
clr.AddReference('RevitAPI') 
from Autodesk.Revit.DB import *
clr.AddReference('RevitAPIUI')

doc=Revit.ActiveDBDocument
uiapp= Revit.ActiveUIApplication
t = Transaction(doc, 'Place an Adaptive Component.')
t.Start()
collector = FilteredElementCollector(doc)
collector.OfCategory(BuiltInCategory.OST_Walls)
t.Commit()
a=collector
```

Does it work in your case?
